name: buildme
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - pip
  - numpy
  - pandas
  - tqdm
  - openpyxl
  - ipykernel
  - matplotlib
  - seaborn
